name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: sudo apt install php{$php-version}-intl

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install
  
    - name: Verify code standards
      run: make phpcs
  
    - name: Run static analysis
      run: make psalm
    
    - name: Unit tests
      run: make phpunit

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
